### PR TITLE
fix: compatible with kube api  1.16+

### PR DESCRIPTION
**Pull request by jiangytcn**
support kube api 1.16+

part of https://github.com/jenkins-x/jx/pull/6385

### CODE REVIEW

**Comment by jiangytcn** [comment]
thanks @ccojocar  can you help me on this ? I cannot find the test case for this repo.

**Comment by abayer** [comment]
@jiangytcn I'll take a look at the failure tomorrow - the problem is in the `jenkins-x.yml`, not your PR.

**Pull request merged**
