### PR TITLE
Fixup postStart.sh to handle spaces in passwords.

### PR DESCRIPTION
**Pull request by AlienResidents**
Quoted variables.
Added NEXUS_BASE_DIR, and NEXUS_REPO_DIR vars.
Implemented shellcheck recommendations for using find, mapfile, and a few others.

### CODE REVIEW

**Comment by sboardwell** [comment]
👍 for the mapfile stuff.

**Comment by AlienResidents** [comment]
@jstrachan Do I need to do anything further on this PR?

**Comment by AlienResidents** [comment]
I don't have visibility to see why this failed, but I'd be happy to take a look, and troubleshoot the issue, if possible.

**Comment by ccojocar** [comment]
@AlienResidents The Jenkins X pipeline file needs to be updated. It seems to be outdated. This is not related to this PR.

**Comment by AlienResidents** [comment]
Thanks for the update @ccojocar .  I have some sporadic spare time to help fix things, if it's wanted.

**Pull request merged**
